---
title: "Report"
output: html_document
date: "2023-11-24"
---

```{r setup, include=FALSE, }
library(frictionless)
library(checkmate)
library(printr)

testrmd::init()

sigplan <- suppressMessages(read_package(here::here("datapackages/sigplan/datapackage.json")))
acoes_planejamento <- read_resource(sigplan, "acoes_planejamento")
programas_planejamento <- read_resource(sigplan, "programas_planejamento")
localizadores_todos_planejamento <- read_resource(sigplan, "localizadores_todos_planejamento")

sisor <- suppressMessages(read_package(here::here("datapackages/sisor/datapackage.json")))
base_qdd_fiscal <- read_resource(sisor, "base_qdd_fiscal")
base_qdd_investimento <- read_resource(sisor, "base_qdd_investimento")
base_qdd_plurianual <- read_resource(sisor, "base_qdd_plurianual")
```

```{r}
stop_on_error <- function(report) {
  if(!report$valid) {
      stop(report$status)
  }
}
```


```{r, printr.help.sections="description", echo=FALSE}
?check_total_orcamento
```

#### Total orçamento fiscal

```{r, echo=FALSE, test=TRUE}
check <- check_total_orcamento_fiscal(base_qdd_fiscal, acoes_planejamento)
check$info
stopifnot(check$valid)
```

#### Total orçamento de investimento

```{r, echo=FALSE, test=TRUE}
check <- check_total_orcamento_investimento(base_qdd_investimento, acoes_planejamento)
check$info
stopifnot(check$valid)
```

#### Total orçamento fiscal plurianual

```{r, echo=FALSE, test=TRUE}
check <- check_total_orcamento_fiscal_plurianual(base_qdd_plurianual, acoes_planejamento)
check$info
stopifnot(check$valid)
```


```{r, printr.help.sections="description", echo=FALSE}
?check_area_tematica_exists
```


#### Programas

```{r, echo=FALSE, test=TRUE}
check <- check_area_tematica_exists_programas(programas_planejamento)
check$info
stopifnot(check$valid)
```

#### Ações

```{r, echo=FALSE, test=TRUE}
check <- check_area_tematica_exists_acoes(acoes_planejamento)
check$info
stopifnot(check$valid)
```

#### Localizadores

```{r, echo=FALSE, test=TRUE, message=FALSE}
check <- check_area_tematica_exists_localizadores(localizadores_todos_planejamento)
check$info
stop_on_error(check)
```
